### ISSUE TITLE
Unhandled REPL handler exception processing message

### ISSUE THREAD

**Issue by henkjanc** [tuhlmann/reagent-material#6]
Hi,
I'm new on clojure/clojurescript. I tried to run your example, but I run into problems regarding piggieback. Shouldnt cider/piggieback be used? (tried to replace it, but it failed too). What else could be wrong here?
Thanks in advance,
KR, 
Henk-Jan

**Environment:**
- Mac OSX
- Java 8 and 12 (both on piggieback, but with different errors)
- lein 2.9.4

**Details Java 8:** 
```
(base) MAC012~/workspace/student00 $ git clone https://github.com/tuhlmann/reagent-(base) MAC012~/workspace/student00/reagent-material $ lein repl
[WARNING] No nREPL middleware descriptor in metadata of #'cemerick.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
nREPL server started on port 60964 on host 127.0.0.1 - nrepl://127.0.0.1:60964
ERROR: Unhandled REPL handler exception processing message {:id a5e47bdd-c1b9-4268-9bc9-c94080b43d4a, :op clone}
java.lang.NullPointerException
	at clojure.core$deref_future.invoke(core.clj:2184)
	at clojure.core$deref.invoke(core.clj:2205)
	at cemerick.piggieback$wrap_cljs_repl$fn__19230.invoke(piggieback.clj:266)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__14877.invoke(middleware.clj:22)
	at nrepl.server$handle_STAR_.invoke(server.clj:19)


=== 
**Details on Java 12**
...

Error loading cemerick.piggieback: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/closure.clj:1:1)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cemerick.piggieback/wrap-cljs-repl in this context, compiling:(/private/var/folders/yy/th4lx8z567s091vkdmltjjl00000gp/T/form-init12604765778905497276.clj:1:3221)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6740)

```

**Comment by tuhlmann** [comment]
I'm afraid I can't be a big help with Clojure anymore. I haven't worked with it for the last 5 years and I don't really know how the landscape changed.

I'm pretty sure I used Java 8 back then.
The Java 12 error points to a missing library. We are still using Java 8 (and Scala) in my current projects so I'm not current- but I remember the discussion about project Jigsaw where they wanted to break Java up into smaller packets. Maybe you need to install the missing javax.xml package?

As how to continue from here, I would use a different project's build setup that is more recent and then try to implant the code you wish to use into that new project. Or maybe looking at a more recent project gives you a clue about what needs updating with the Clojure dependencies.

Sorry I can't offer more help,
Torsten.

**Comment by henkjanc** [comment]
Torsten thanks for your quick answer. Dependencies... they break ;-) You have been very helpful already. Now I know it's not just me overlooking something simple. I will have a look around on github. Or maybe try to fix it. In that case I will let you know.
Henk-Jan
